2025-02-03 13:31:35,019 - INFO - [server.py:29] - Starting MCC Server...
2025-02-03 13:31:46,634 - INFO - [server.py:69] - New connection from ('192.168.0.126', 50538)
Exception in thread Thread-2 (start):
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
2025-02-03 13:31:53,293 - INFO - [server.py:354] - RDP Start request received. Host: 192.168.0.149, Port: 5900
2025-02-03 13:31:53,293 - INFO - [server.py:368] - Creating new RDP server instance...
Initializing RDP Server on 0.0.0.0:5900
2025-02-03 13:31:53,293 - INFO - [server.py:371] - Creating RDP server thread...
2025-02-03 13:31:53,293 - INFO - [server.py:375] - Starting RDP server thread...
RDP Server binding to 0.0.0.0:5900
RDP Server startup error: [WinError 10022] An invalid argument was supplied
    self.run()
  File "C:\Program Files\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\UserStud\PycharmProjects\pythonProject\serverRDP.py", line 41, in start
    self.socket.bind(self.host)
OSError: [WinError 10022] An invalid argument was supplied
2025-02-03 13:31:54,294 - ERROR - [server.py:396] - Failed to start RDP server: RDP server thread failed to start
2025-02-03 13:31:54,294 - INFO - [server.py:399] - Attempting to stop failed RDP server...
Stopping RDP server...
RDP server stopped successfully
2025-02-03 13:31:55,686 - INFO - [server.py:106] - Connection closed from ('192.168.0.126', 50538)
